name: Extracting VerCode - JP

on:
  push:
    branches: []
  pull_request:
    branches: []
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/xdeadboy666x/FGO-VerCode-extractor/JP/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v4

      - name: Execute main script
        run: python3 main.py

      - name: Commit & push changes to branch JP
        uses: actions-js/push@master
        with:
          force: true
          branch: "JP"
          github_token: ${{ secrets.TOKEN_REPO }}
