name: Extracting VerCode - NA

on:
  push:
    branches: [NA]
  pull_request:
    branches: [NA]
  schedule:
    - cron: "05 04 * * *"
    - cron: "05 10 * * *"
    - cron: "05 14 * * *"
    - cron: "50 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4
        run: |
          pip install -r requirements.txt
          python3 main.py

      - name: Commit & push changes to branch NA
        uses: actions-js/push@master
        with:
          force: true
          branch: "NA"
          github_token: ${{ secrets.TOKEN_REPO }}

