name: Extracting VerCode - NA

on:
  push:
    branches: [NA]
  pull_request:
    branches: [NA]
  workflow_dispatch:
  schedule:
    - cron:'16 2,13 * * *'
    - cron:'15 1,14 * * *'
    - cron:'15 6,18 * * *'
    - cron:'15 7,19 * * *'
    
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11]
  
  steps:
    - name: Install Requirements
      run: pip install -r https://github.com/xdeadboy666x/FGO-VerCode-extractor/raw/NA/requirements.txt

    - name: Getting files from Repo
      uses: actions/checkout@v4

    - name: Execute main script
      run: python3 main.py

    - name: Commit & push changes to branch JP
      uses: actions-js/push@master
    
      with:   
      force: true
      branch: "NA"
      github_token: ${{ secrets.TOKEN_REPO }}
