name: Extracting VerCode - NA

on:
  push:
    branches: [NA]
  pull_request:
    branches: [NA]
  schedule:
    - cron: '30 1,13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/xdeadboy666x/FGO-VerCode/NA/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v4

      - name: Execute main script
        run: python3 main.py

      - name: Commit & push changes to branch NA
        uses: actions-js/push@master
        with:
          force: true
          branch: "NA"
          github_token: ${{ secrets.TOKEN_REPO }}
